name: Test,Build,Publish

on:
  workflow_dispatch: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies with Yarn
        run: yarn install  # Use Yarn to install dependencies
      - name: Run Tests with Yarn
        run: yarn test  # Use Yarn to run tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: yarn cypress:run
          browser: chrome

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies with Yarn
        run: yarn install  # Use Yarn to install dependencies
      - name: Publish to npm with Yarn
        run: yarn publish --access public  # Use Yarn to publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
