name: Update Package Version and Make PR to dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version increment (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

permissions: write-all

jobs:
    
  update-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/pre-dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4        
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use the Node.js version you need

      - name: Config git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git config pull.ff true
          echo "${{ github.ref }}"           


      - name: Update Package Version
        run: |
          version_increment="${{ github.event.inputs.version }}"
          echo  $version_increment
          npm version $version_increment            

      - name: Stage files
        run: |
          git add .
      
      - name: Commit staged files [updated package.json]
        run: |
          set +e  # Disable exit-on-error temporarily
          git commit -m "Update package version [skip ci]"
          set -e  # Re-enable exit-on-error        


      - name: Push updated package.json
        run: |
          git push origin ${{ github.ref }} 
      
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: ${{ github.ref }}


      - name: Make PR to dev
        run: gh pr create --base dev --title "PR from ${{ github.ref }} to dev" --body "Automated PR from ${{ github.ref }} to dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
  
